name: Raios
version: 1.0
main: com.itakinn.TKNRaios
author: iTakinn
commands:
  raios:
    description: Ativa ou desativa raios sobre um jogador
    usage: /raios <player>
    permission: TKNRaios.raios
  raiosolhar:
    description: Ativa ou desativa raios onde o jogador que estiver olhando
    usage: /raiosolhar
    permission: TKNRaios.raiosolhar
  subir:
    description: Teleporta o jogador para cima
    usage: /subir
    permission: TKNRaios.subir

permissions:
  TKNRaios.raios:
    description: Permite que o jogador ative ou desative raios sobre outro jogador
    default: op
  TKNRaios.raiosolhar:
    description: Permite que o jogador ative ou desative raios onde estiver olhando
    default: op
  TKNRaios.subir:
    description: Permite que o jogador se teleporte para cima
    default: op